# Generated by Django 5.1.1 on 2024-09-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "categories"},
        ),
    ]
