# Generated by Django 5.1.1 on 2024-09-16 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("annee", models.IntegerField()),
                ("couleur", models.CharField(max_length=50)),
                ("type_carburant", models.CharField(max_length=50)),
                ("capacite", models.IntegerField()),
                ("prix_par_jour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponible", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("photo", models.ImageField(upload_to="vehicules/")),
                ("immatriculation", models.CharField(max_length=50, unique=True)),
                ("kilometrage", models.IntegerField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("reservé", "Réservé"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="product", name="category",),
        migrations.RemoveField(model_name="order", name="customer",),
        migrations.RemoveField(model_name="order", name="product",),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=15, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                (
                    "permis_conduire",
                    models.FileField(
                        blank=True, null=True, upload_to="permis_conduire/"
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                ("prix_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirmée", "Confirmée"),
                            ("annulée", "Annulée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_reservation", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.client"
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.vehicule"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateTimeField(auto_now_add=True)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("carte", "Carte de crédit"),
                            ("virement", "Virement bancaire"),
                            ("espèce", "Espèce"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="store.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContratLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_signature", models.DateTimeField(auto_now_add=True)),
                ("conditions", models.TextField()),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrat",
                        to="store.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueVehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evenement", models.DateTimeField()),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("entretien", "Entretien"),
                            ("réparation", "Réparation"),
                            ("incident", "Incident"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="store.vehicule",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Customer",),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="Product",),
    ]
