# Generated by Django 5.1.1 on 2024-09-17 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_client_date_inscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="date_inscription",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
