# Generated by Django 5.1.1 on 2024-09-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_client_date_inscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client", name="email", field=models.EmailField(max_length=254),
        ),
    ]
